package javaswingdev.main;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javaswingdev.FontAwesome;
import javaswingdev.sm3d.ModelItem;
import javaswingdev.sm3d.SocialMediaEvent;

/**
 *
 * @author RAVEN
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        getContentPane().setBackground(new Color(240, 240, 240));
        socialMedia3D1.addItem(new ModelItem("Youtube", "https://www.youtube.com/c/HelloWorld-Raven/videos", FontAwesome.YOUTUBE_PLAY, Color.RED, new Color(204, 0, 0), new Color(229, 0, 0)));
        socialMedia3D1.addItem(new ModelItem("Website", "", FontAwesome.GLOBE, new Color(255, 207, 0), new Color(204, 165, 0), new Color(229, 186, 0)));
        socialMedia3D1.addItem(new ModelItem("GitHub", "https://github.com/DJ-Raven", FontAwesome.GITHUB, new Color(38, 38, 38), new Color(16, 16, 16), new Color(40, 40, 40)));
        socialMedia3D1.addItem(new ModelItem("Facebook", "https://www.facebook.com/Java-Swing-Programming-107380654949202", FontAwesome.FACEBOOK, new Color(23, 120, 242), new Color(17, 93, 188), new Color(20, 106, 214)));
        socialMedia3D1.addItem(new ModelItem("Instagram", "", FontAwesome.INSTAGRAM, new Color(193, 53, 132), new Color(140, 38, 96), new Color(165, 44, 113)));
        socialMedia3D1.addItem(new ModelItem("Twitter", "", FontAwesome.TWITTER, new Color(29, 161, 242), new Color(22, 125, 188), new Color(25, 142, 214)));
        socialMedia3D1.addEvent(new SocialMediaEvent() {
            @Override
            public void selected(ModelItem item) {
                try {
                    Desktop.getDesktop().browse(new URI(item.getUrl()));
                } catch (Exception e) {
                    System.err.println(e);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        socialMedia3D1 = new javaswingdev.sm3d.SocialMedia3D();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(socialMedia3D1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(socialMedia3D1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.sm3d.SocialMedia3D socialMedia3D1;
    // End of variables declaration//GEN-END:variables
}
